// This file is automatically generated. Do not edit.
package net.socialgamer.cah.handlers;

import java.util.HashMap;
import java.util.Map;


public class Handlers {
  public final static Map<String, Class<? extends Handler>> LIST;

  static {
    LIST = new HashMap<String, Class<? extends Handler>>();
    LIST.put(ChatHandler.OP, ChatHandler.class);
    LIST.put(BanHandler.OP, BanHandler.class);
    LIST.put(JoinGameHandler.OP, JoinGameHandler.class);
    LIST.put(AdminSetVerboseLog.OP, AdminSetVerboseLog.class);
    LIST.put(GameListHandler.OP, GameListHandler.class);
    LIST.put(LeaveGameHandler.OP, LeaveGameHandler.class);
    LIST.put(ChangeGameOptionHandler.OP, ChangeGameOptionHandler.class);
    LIST.put(StartGameHandler.OP, StartGameHandler.class);
    LIST.put(PlayCardHandler.OP, PlayCardHandler.class);
    LIST.put(ResetCardsHandler.OP, ResetCardsHandler.class);
    LIST.put(GetCardsHandler.OP, GetCardsHandler.class);
    LIST.put(KickHandler.OP, KickHandler.class);
    LIST.put(NamesHandler.OP, NamesHandler.class);
    LIST.put(GetGameInfoHandler.OP, GetGameInfoHandler.class);
    LIST.put(RegisterHandler.OP, RegisterHandler.class);
    LIST.put(CreateGameHandler.OP, CreateGameHandler.class);
    LIST.put(LogoutHandler.OP, LogoutHandler.class);
    LIST.put(FirstLoadHandler.OP, FirstLoadHandler.class);
    LIST.put(GameChatHandler.OP, GameChatHandler.class);
    LIST.put(JudgeSelectHandler.OP, JudgeSelectHandler.class);
  }
}
